#! /bin/bash
set -eu

function rm_items {
  local item
  for item in "${@}"; do
    if [ -f "${item}" ]; then
      rm -v "${item}"
    fi
    if [ -d "${item}" ]; then
      rmdir --ignore-fail-on-non-empty -p "${item}"
    fi
  done
}

function uninstall_gitk {
  gitdir=${HOME}/.config/git
  rm_items \
    "${gitdir}"/gitk-{light,light2,light3,dark,dark2,dark3} \
    "${gitdir}"
}

function uninstall_neovim {
  neovimdir=${HOME}/.config/nvim
  rm_items \
    "${neovimdir}"/colors/colorific.vim \
    "${neovimdir}"/colors \
    "${neovimdir}"/autoload/airline/themes/colorific.vim \
    "${neovimdir}"/autoload/airline/themes
}

function uninstall_alacritty {
  alacrittydir=${HOME}/.config/alacritty
  rm_items \
    "${alacrittydir}"/colorific.yml \
    "${alacrittydir}"
}

function uninstall_kitty {
  kittydir=${HOME}/.config/kitty/themes
  rm_items \
    "${kittydir}"/{light,light2,light3,dark,dark2,dark3}.conf \
    "${kittydir}"
}

function uninstall_tmux {
  tmuxdir=${HOME}/.tmux
  rm_items \
    "${tmuxdir}"/{light,light2,light3,dark,dark2,dark3}.tmuxtheme \
    "${tmuxdir}"
}

function uninstall_vim {
  vimdir=${HOME}/.vim
  rm_items \
    "${vimdir}"/colors/colorific.vim \
    "${vimdir}"/colors \
    "${vimdir}"/autoload/airline/themes/colorific.vim \
    "${vimdir}"/autoload/airline/themes
}

function print_usage {
  echo "./uninstall usage:"
  echo "  -a|--alacritty   uninstall alacritty files"
  echo "  -g|--gitk        uninstall gitk files"
  echo "  -k|--kitty       uninstall kitty files"
  echo "  -n|--neovim      uninstall neovim files"
  echo "  -t|--tmux        uninstall tmux files"
  echo "  -v|--vim         uninstall vim files"
  echo "  -h|--help        print this message"
}

OPTIONS=aghkntv
LONGOPTIONS=alacritty,git,help,kitty,neovim,tmux,vim
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "${0}" -- "${@}")
eval set -- "${PARSED}"

if [ ${#} -eq 1 ]; then
  uninstall_alacritty
  uninstall_gitk
  uninstall_kitty
  uninstall_neovim
  uninstall_tmux
  uninstall_vim
fi

while [ ${#} -ge 1 ]; do
  case ${1} in
    -a|--alacritty)
      uninstall_alacritty
      shift
      ;;
    -g|--gitk)
      uninstall_gitk
      shift
      ;;
    -k|--kitty)
      uninstall_kitty
      shift
      ;;
    -n|--neovim)
      uninstall_neovim
      shift
      ;;
    -t|--tmux)
      uninstall_tmux
      shift
      ;;
    -v|--vim)
      uninstall_vim
      shift
      ;;
    -h|--help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "ERROR: invalid flag ${2@Q}."
      exit 3
      ;;
  esac
done

echo "Done."
