#! /bin/bash
set -eu

function rm_items {
  local item
  for item in "${@}"; do
    if [ -f "${item}" ]; then
      rm -v "${item}"
    fi
    if [ -d "${item}" ]; then
      rmdir --ignore-fail-on-non-empty -p "${item}"
    fi
  done
}

function install_gitk {
  gitdir=${HOME}/.config/git
  rm_items \
    "${gitdir}"/gitk-{light,light2,light3,dark,dark2,dark3} \
    "${gitdir}"
}

function install_neovim {
  neovimdir=${HOME}/.config/nvim
  rm_items \
    "${neovimdir}"/colors/colorific.vim \
    "${neovimdir}"/colors \
    "${neovimdir}"/autoload/airline/themes/colorific.vim \
    "${neovimdir}"/autoload/airline/themes
}

function install_kitty {
  kittydir=${HOME}/.config/kitty/themes
  rm_items \
    "${kittydir}"/{light,light2,light3,dark,dark2,dark3}.conf \
    "${kittydir}"
}

function install_tmux {
  tmuxdir=${HOME}/.tmux
  rm_items \
    "${tmuxdir}"/{light,light2,light3,dark,dark2,dark3}.tmuxtheme \
    "${tmuxdir}"
}

function install_vim {
  vimdir=${HOME}/.vim
  rm_items \
    "${vimdir}"/colors/colorific.vim \
    "${vimdir}"/colors \
    "${vimdir}"/autoload/airline/themes/colorific.vim \
    "${vimdir}"/autoload/airline/themes
}

function print_usage {
  echo "./install usage:"
  echo "  -g|--gitk        install gitk files"
  echo "  -k|--kitty       install kitty files"
  echo "  -n|--neovim      install neovim files"
  echo "  -t|--tmux        install tmux files"
  echo "  -v|--vim         install vim files"
  echo "  -h|--help        print this message"
}

OPTIONS=ghkntv
LONGOPTIONS=git,help,kitty,neovim,tmux,vim
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "${0}" -- "${@}")
eval set -- "${PARSED}"

if [ ${#} -eq 1 ]; then
  install_gitk
  install_kitty
  install_neovim
  install_tmux
  install_vim
fi

while [ ${#} -ge 1 ]; do
  case ${1} in
    -g|--gitk)
      install_gitk
      shift
      ;;
    -k|--kitty)
      install_kitty
      shift
      ;;
    -n|--neovim)
      install_neovim
      shift
      ;;
    -t|--tmux)
      install_tmux
      shift
      ;;
    -v|--vim)
      install_vim
      shift
      ;;
    -h|--help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "ERROR: invalid flag ${2@Q}."
      exit 3
      ;;
  esac
done

echo "Done."
